CREATE DATABASE IF NOT EXISTS school_management_system;
USE school_management_system;

CREATE TABLE IF NOT EXISTS departments (
    department_id INT AUTO_INCREMENT PRIMARY KEY,
    department_name VARCHAR(120) NOT NULL,
    office_location VARCHAR(160) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
    course_id INT AUTO_INCREMENT PRIMARY KEY,
    course_code VARCHAR(40) NOT NULL,
    course_name VARCHAR(160) NOT NULL,
    department_id INT NULL,
    total_units DECIMAL(6,2) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS school_years (
    school_year_id INT AUTO_INCREMENT PRIMARY KEY,
    school_year VARCHAR(40) NOT NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS semesters (
    semester_id INT AUTO_INCREMENT PRIMARY KEY,
    semester_name VARCHAR(60) NOT NULL,
    is_current TINYINT(1) NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sections (
    section_id INT AUTO_INCREMENT PRIMARY KEY,
    section_name VARCHAR(80) NOT NULL,
    course_id INT NULL,
    year_level INT NULL,
    section_year_level INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    student_number VARCHAR(40) NULL,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(160) NULL,
    course_id INT NULL,
    year_level INT NULL,
    contact_number VARCHAR(20) NULL,
    section_id INT NULL,
    current_year_level INT NOT NULL DEFAULT 1,
    full_name VARCHAR(180) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS professors (
    professor_id INT AUTO_INCREMENT PRIMARY KEY,
    employee_number VARCHAR(40) NULL,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(160) NULL,
    department_id INT NULL,
    contact_number VARCHAR(20) NULL,
    full_name VARCHAR(180) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staffs (
    staff_id INT AUTO_INCREMENT PRIMARY KEY,
    employee_number VARCHAR(40) NULL,
    first_name VARCHAR(80) NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NULL,
    email VARCHAR(160) NULL,
    department_id INT NULL,
    full_name VARCHAR(180) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    employee_number VARCHAR(40) NULL,
    first_name VARCHAR(80) NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NULL,
    email VARCHAR(160) NULL,
    full_name VARCHAR(180) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password VARCHAR(160) NOT NULL,
    role VARCHAR(20) NOT NULL,
    full_name VARCHAR(180) NULL,
    student_id INT NULL,
    professor_id INT NULL,
    admin_id INT NULL,
    staff_id INT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subjects (
    subject_id INT AUTO_INCREMENT PRIMARY KEY,
    subject_code VARCHAR(40) NOT NULL,
    subject_name VARCHAR(180) NOT NULL,
    units DECIMAL(6,2) NOT NULL DEFAULT 3.00,
    department_id INT NULL,
    professor_id INT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
    class_id INT AUTO_INCREMENT PRIMARY KEY,
    subject_id INT NOT NULL,
    professor_id INT NULL,
    section_id INT NULL,
    semester_id INT NULL,
    school_year_id INT NULL,
    room VARCHAR(50) NULL,
    capacity INT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS class_schedules (
    class_schedule_id INT AUTO_INCREMENT PRIMARY KEY,
    class_id INT NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room VARCHAR(50) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS enrollments (
    enrollment_id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    class_id INT NOT NULL,
    enrollment_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'enrolled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS grades (
    grade_id INT AUTO_INCREMENT PRIMARY KEY,
    enrollment_id INT NOT NULL,
    midterm_performance DECIMAL(6,2) NULL,
    midterm_attendance DECIMAL(6,2) NULL,
    midterm_written_works DECIMAL(6,2) NULL,
    midterm_exam DECIMAL(6,2) NULL,
    finals_performance DECIMAL(6,2) NULL,
    finals_attendance DECIMAL(6,2) NULL,
    finals_written_works DECIMAL(6,2) NULL,
    finals_exam DECIMAL(6,2) NULL,
    midterm_raw_score DECIMAL(6,2) NULL,
    finals_raw_score DECIMAL(6,2) NULL,
    final_raw_grade DECIMAL(6,2) NULL,
    final_grade DECIMAL(6,2) NULL,
    grade_value DECIMAL(6,2) NULL,
    remarks VARCHAR(40) NULL,
    prelim DECIMAL(6,2) NULL,
    midterm DECIMAL(6,2) NULL,
    finals DECIMAL(6,2) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE departments ADD COLUMN IF NOT EXISTS office_location VARCHAR(160) NULL;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE courses ADD COLUMN IF NOT EXISTS course_code VARCHAR(40) NULL;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS total_units DECIMAL(6,2) NULL;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE school_years ADD COLUMN IF NOT EXISTS is_current TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE school_years ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE semesters ADD COLUMN IF NOT EXISTS is_current TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE semesters ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE sections ADD COLUMN IF NOT EXISTS year_level INT NULL;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS section_year_level INT NOT NULL DEFAULT 1;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'open';

ALTER TABLE students ADD COLUMN IF NOT EXISTS student_number VARCHAR(40) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS full_name VARCHAR(180) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS course_id INT NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS year_level INT NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS contact_number VARCHAR(20) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS section_id INT NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS current_year_level INT NOT NULL DEFAULT 1;
ALTER TABLE students ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE professors ADD COLUMN IF NOT EXISTS employee_number VARCHAR(40) NULL;
ALTER TABLE professors ADD COLUMN IF NOT EXISTS contact_number VARCHAR(20) NULL;
ALTER TABLE professors ADD COLUMN IF NOT EXISTS full_name VARCHAR(180) NULL;
ALTER TABLE professors ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE staffs ADD COLUMN IF NOT EXISTS employee_number VARCHAR(40) NULL;
ALTER TABLE staffs ADD COLUMN IF NOT EXISTS first_name VARCHAR(80) NULL;
ALTER TABLE staffs ADD COLUMN IF NOT EXISTS middle_name VARCHAR(80) NULL;
ALTER TABLE staffs ADD COLUMN IF NOT EXISTS last_name VARCHAR(80) NULL;
ALTER TABLE staffs ADD COLUMN IF NOT EXISTS full_name VARCHAR(180) NULL;
ALTER TABLE staffs ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE admins ADD COLUMN IF NOT EXISTS employee_number VARCHAR(40) NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS first_name VARCHAR(80) NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS middle_name VARCHAR(80) NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS last_name VARCHAR(80) NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS full_name VARCHAR(180) NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(180) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS student_id INT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS professor_id INT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_id INT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS staff_id INT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE subjects ADD COLUMN IF NOT EXISTS professor_id INT NULL;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE classes ADD COLUMN IF NOT EXISTS semester_id INT NULL;
ALTER TABLE classes ADD COLUMN IF NOT EXISTS school_year_id INT NULL;
ALTER TABLE classes ADD COLUMN IF NOT EXISTS capacity INT NULL;
ALTER TABLE classes ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'open';

ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS enrollment_date DATE NULL;
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'enrolled';

ALTER TABLE grades ADD COLUMN IF NOT EXISTS midterm_performance DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS midterm_attendance DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS midterm_written_works DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS midterm_exam DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS finals_performance DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS finals_attendance DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS finals_written_works DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS finals_exam DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS midterm_raw_score DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS finals_raw_score DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS final_raw_grade DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS final_grade DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS grade_value DECIMAL(6,2) NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS remarks VARCHAR(40) NULL;
